/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserId = IDL.Principal;
export const Visibility = IDL.Variant({
  'everyone' : IDL.Null,
  'followersOnly' : IDL.Null,
  'friendsOnly' : IDL.Null,
  'customList' : IDL.Null,
});
export const StoryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'username' : IDL.Text,
  'aboutWebsite' : IDL.Opt(IDL.Text),
  'birthdate' : IDL.Opt(IDL.Text),
  'isOfficialPage' : IDL.Bool,
  'isVerified' : IDL.Bool,
  'aboutBio' : IDL.Opt(IDL.Text),
  'aboutWork' : IDL.Opt(IDL.Text),
  'aboutLocation' : IDL.Opt(IDL.Text),
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
  'visibility' : Visibility,
  'coverPhotoUrl' : IDL.Opt(IDL.Text),
  'aboutEducation' : IDL.Opt(IDL.Text),
});
export const StoryView = IDL.Record({
  'id' : StoryId,
  'expiresAt' : Timestamp,
  'viewedByMe' : IDL.Bool,
  'createdAt' : Timestamp,
  'author' : UserProfile,
  'imageUrl' : IDL.Text,
  'textOverlay' : IDL.Opt(IDL.Text),
  'viewCount' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'pendingReports' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'verifiedUsers' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPosts' : IDL.Nat,
  'totalStories' : IDL.Nat,
});
export const CommentView = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'updatedAt' : Timestamp,
  'replyCount' : IDL.Nat,
  'parentId' : IDL.Opt(CommentId),
  'postId' : PostId,
});
export const ConversationId = IDL.Text;
export const ConversationSummary = IDL.Record({
  'lastMessageAt' : Timestamp,
  'otherUsername' : IDL.Text,
  'lastMessagePreview' : IDL.Text,
  'otherUserId' : UserId,
  'conversationId' : ConversationId,
});
export const PostView = IDL.Record({
  'id' : PostId,
  'authorVerified' : IDL.Bool,
  'content' : IDL.Text,
  'authorProfilePhoto' : IDL.Opt(IDL.Text),
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Opt(IDL.Text),
  'visibility' : Visibility,
  'isPinned' : IDL.Bool,
});
export const MessageId = IDL.Nat;
export const MessageReactionView = IDL.Record({
  'reactor' : UserProfile,
  'reaction' : IDL.Text,
});
export const MessageView = IDL.Record({
  'id' : MessageId,
  'encryptedContent' : IDL.Vec(IDL.Nat8),
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'conversationId' : ConversationId,
  'senderId' : UserId,
  'readAt' : IDL.Opt(Timestamp),
});
export const ReactionType = IDL.Variant({
  'sad' : IDL.Null,
  'wow' : IDL.Null,
  'angry' : IDL.Null,
  'haha' : IDL.Null,
  'like' : IDL.Null,
  'love' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'verified' : IDL.Record({}),
  'like' : IDL.Record({ 'postId' : PostId }),
  'share' : IDL.Record({ 'postId' : PostId }),
  'comment' : IDL.Record({ 'commentId' : CommentId, 'postId' : PostId }),
  'mention' : IDL.Record({ 'postId' : PostId }),
  'friendRequest' : IDL.Record({ 'requestId' : IDL.Nat }),
  'reaction' : IDL.Record({ 'reaction' : ReactionType, 'postId' : PostId }),
  'follow' : IDL.Record({}),
});
export const NotificationView = IDL.Record({
  'id' : NotificationId,
  'actorName' : IDL.Text,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'actorId' : UserId,
});
export const FriendRequestId = IDL.Nat;
export const FriendRequestView = IDL.Record({
  'id' : FriendRequestId,
  'to' : UserProfile,
  'status' : IDL.Text,
  'from' : UserProfile,
  'createdAt' : Timestamp,
});
export const PollOptionResult = IDL.Record({
  'id' : IDL.Nat,
  'votes' : IDL.Nat,
  'text' : IDL.Text,
  'percent' : IDL.Float64,
});
export const PollResults = IDL.Record({
  'totalVotes' : IDL.Nat,
  'myVote' : IDL.Opt(IDL.Nat),
  'options' : IDL.Vec(PollOptionResult),
});
export const PostStats = IDL.Record({
  'shares' : IDL.Nat,
  'likes' : IDL.Nat,
  'comments' : IDL.Nat,
});
export const ReportView = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'reportedPost' : IDL.Opt(PostView),
  'reportedUser' : IDL.Opt(UserProfile),
  'createdAt' : Timestamp,
  'reporter' : UserProfile,
  'reason' : IDL.Text,
});
export const StoryFeed = IDL.Record({
  'stories' : IDL.Vec(StoryView),
  'author' : UserProfile,
  'hasUnviewed' : IDL.Bool,
});
export const HashtagStat = IDL.Record({
  'postCount' : IDL.Nat,
  'hashtag' : IDL.Text,
});
export const ResolveAction = IDL.Variant({
  'banUser' : IDL.Null,
  'deleteContent' : IDL.Null,
  'dismiss' : IDL.Null,
  'suspendUser' : IDL.Null,
});
export const RespondAction = IDL.Variant({
  'accept' : IDL.Null,
  'block' : IDL.Null,
  'decline' : IDL.Null,
});
export const SearchResults = IDL.Record({
  'users' : IDL.Vec(UserProfile),
  'posts' : IDL.Vec(PostView),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'banUser' : IDL.Func([UserId], [IDL.Bool], []),
  'blockUser' : IDL.Func([UserId], [], []),
  'cancelFriendRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createOfficialPost' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
      [],
    ),
  'createPoll' : IDL.Func([PostId, IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'createPost' : IDL.Func(
      [IDL.Text, Visibility, IDL.Vec(UserId), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
      [],
    ),
  'createStory' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [StoryView], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'editComment' : IDL.Func([CommentId, IDL.Text], [], []),
  'editPost' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
  'followUser' : IDL.Func([UserId], [IDL.Bool], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllUsers' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getComments' : IDL.Func([PostId], [IDL.Vec(CommentView)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getFriendRequestStatus' : IDL.Func([UserId], [IDL.Text], ['query']),
  'getHashtagPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'getLikes' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
  'getMessageReactions' : IDL.Func(
      [MessageId],
      [IDL.Vec(MessageReactionView)],
      ['query'],
    ),
  'getMessages' : IDL.Func([UserId], [IDL.Vec(MessageView)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyReaction' : IDL.Func([PostId], [IDL.Opt(ReactionType)], []),
  'getMyStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], []),
  'getOfficialPage' : IDL.Func([], [UserProfile], ['query']),
  'getOfficialPagePosts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PostView)],
      ['query'],
    ),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(FriendRequestView)], ['query']),
  'getPollResults' : IDL.Func([IDL.Nat], [PollResults], ['query']),
  'getPostStats' : IDL.Func([PostId], [PostStats], ['query']),
  'getReactions' : IDL.Func(
      [PostId],
      [IDL.Vec(IDL.Tuple(ReactionType, IDL.Nat))],
      ['query'],
    ),
  'getReports' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(ReportView)], ['query']),
  'getSavedPosts' : IDL.Func([], [IDL.Vec(PostView)], []),
  'getSentRequests' : IDL.Func([], [IDL.Vec(FriendRequestView)], ['query']),
  'getShares' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getStoriesFeed' : IDL.Func([], [IDL.Vec(StoryFeed)], ['query']),
  'getStoryViewers' : IDL.Func([IDL.Nat], [IDL.Vec(UserProfile)], ['query']),
  'getTrendingHashtags' : IDL.Func([], [IDL.Vec(HashtagStat)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], []),
  'getUserPosts' : IDL.Func([UserId], [IDL.Vec(PostView)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'grantVerification' : IDL.Func([UserId], [IDL.Bool], []),
  'hasLiked' : IDL.Func([PostId], [IDL.Bool], []),
  'isBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isVerified' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'markMessageRead' : IDL.Func([MessageId], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'pinPost' : IDL.Func([PostId], [IDL.Bool], []),
  'reactToMessage' : IDL.Func([MessageId, ReactionType], [IDL.Bool], []),
  'reactToPost' : IDL.Func([PostId, ReactionType], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'removeMessageReaction' : IDL.Func([MessageId], [IDL.Bool], []),
  'removeReaction' : IDL.Func([PostId], [], []),
  'replyToComment' : IDL.Func([CommentId, IDL.Text], [CommentId], []),
  'reportPost' : IDL.Func([PostId, IDL.Text], [], []),
  'reportUser' : IDL.Func([UserId, IDL.Text], [], []),
  'resolveReport' : IDL.Func([IDL.Nat, ResolveAction], [IDL.Bool], []),
  'respondFriendRequest' : IDL.Func([IDL.Nat, RespondAction], [IDL.Bool], []),
  'revokeVerification' : IDL.Func([UserId], [IDL.Bool], []),
  'savePost' : IDL.Func([PostId], [], []),
  'searchContent' : IDL.Func([IDL.Text], [SearchResults], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'sendMessage' : IDL.Func([UserId, IDL.Vec(IDL.Nat8)], [MessageId], []),
  'sharePost' : IDL.Func([PostId], [], []),
  'suspendUser' : IDL.Func([UserId, IDL.Nat], [IDL.Bool], []),
  'unblockUser' : IDL.Func([UserId], [], []),
  'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'unpinPost' : IDL.Func([], [IDL.Bool], []),
  'unsavePost' : IDL.Func([PostId], [], []),
  'unsharePost' : IDL.Func([PostId], [], []),
  'updateAbout' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'updateCoverPhoto' : IDL.Func([IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, Visibility], [IDL.Bool], []),
  'updateProfilePhoto' : IDL.Func([IDL.Text], [], []),
  'viewStory' : IDL.Func([IDL.Nat], [], []),
  'votePoll' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserId = IDL.Principal;
  const Visibility = IDL.Variant({
    'everyone' : IDL.Null,
    'followersOnly' : IDL.Null,
    'friendsOnly' : IDL.Null,
    'customList' : IDL.Null,
  });
  const StoryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'username' : IDL.Text,
    'aboutWebsite' : IDL.Opt(IDL.Text),
    'birthdate' : IDL.Opt(IDL.Text),
    'isOfficialPage' : IDL.Bool,
    'isVerified' : IDL.Bool,
    'aboutBio' : IDL.Opt(IDL.Text),
    'aboutWork' : IDL.Opt(IDL.Text),
    'aboutLocation' : IDL.Opt(IDL.Text),
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
    'visibility' : Visibility,
    'coverPhotoUrl' : IDL.Opt(IDL.Text),
    'aboutEducation' : IDL.Opt(IDL.Text),
  });
  const StoryView = IDL.Record({
    'id' : StoryId,
    'expiresAt' : Timestamp,
    'viewedByMe' : IDL.Bool,
    'createdAt' : Timestamp,
    'author' : UserProfile,
    'imageUrl' : IDL.Text,
    'textOverlay' : IDL.Opt(IDL.Text),
    'viewCount' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'pendingReports' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'verifiedUsers' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPosts' : IDL.Nat,
    'totalStories' : IDL.Nat,
  });
  const CommentView = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'updatedAt' : Timestamp,
    'replyCount' : IDL.Nat,
    'parentId' : IDL.Opt(CommentId),
    'postId' : PostId,
  });
  const ConversationId = IDL.Text;
  const ConversationSummary = IDL.Record({
    'lastMessageAt' : Timestamp,
    'otherUsername' : IDL.Text,
    'lastMessagePreview' : IDL.Text,
    'otherUserId' : UserId,
    'conversationId' : ConversationId,
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'authorVerified' : IDL.Bool,
    'content' : IDL.Text,
    'authorProfilePhoto' : IDL.Opt(IDL.Text),
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Opt(IDL.Text),
    'visibility' : Visibility,
    'isPinned' : IDL.Bool,
  });
  const MessageId = IDL.Nat;
  const MessageReactionView = IDL.Record({
    'reactor' : UserProfile,
    'reaction' : IDL.Text,
  });
  const MessageView = IDL.Record({
    'id' : MessageId,
    'encryptedContent' : IDL.Vec(IDL.Nat8),
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'conversationId' : ConversationId,
    'senderId' : UserId,
    'readAt' : IDL.Opt(Timestamp),
  });
  const ReactionType = IDL.Variant({
    'sad' : IDL.Null,
    'wow' : IDL.Null,
    'angry' : IDL.Null,
    'haha' : IDL.Null,
    'like' : IDL.Null,
    'love' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'verified' : IDL.Record({}),
    'like' : IDL.Record({ 'postId' : PostId }),
    'share' : IDL.Record({ 'postId' : PostId }),
    'comment' : IDL.Record({ 'commentId' : CommentId, 'postId' : PostId }),
    'mention' : IDL.Record({ 'postId' : PostId }),
    'friendRequest' : IDL.Record({ 'requestId' : IDL.Nat }),
    'reaction' : IDL.Record({ 'reaction' : ReactionType, 'postId' : PostId }),
    'follow' : IDL.Record({}),
  });
  const NotificationView = IDL.Record({
    'id' : NotificationId,
    'actorName' : IDL.Text,
    'notifType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'actorId' : UserId,
  });
  const FriendRequestId = IDL.Nat;
  const FriendRequestView = IDL.Record({
    'id' : FriendRequestId,
    'to' : UserProfile,
    'status' : IDL.Text,
    'from' : UserProfile,
    'createdAt' : Timestamp,
  });
  const PollOptionResult = IDL.Record({
    'id' : IDL.Nat,
    'votes' : IDL.Nat,
    'text' : IDL.Text,
    'percent' : IDL.Float64,
  });
  const PollResults = IDL.Record({
    'totalVotes' : IDL.Nat,
    'myVote' : IDL.Opt(IDL.Nat),
    'options' : IDL.Vec(PollOptionResult),
  });
  const PostStats = IDL.Record({
    'shares' : IDL.Nat,
    'likes' : IDL.Nat,
    'comments' : IDL.Nat,
  });
  const ReportView = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'reportedPost' : IDL.Opt(PostView),
    'reportedUser' : IDL.Opt(UserProfile),
    'createdAt' : Timestamp,
    'reporter' : UserProfile,
    'reason' : IDL.Text,
  });
  const StoryFeed = IDL.Record({
    'stories' : IDL.Vec(StoryView),
    'author' : UserProfile,
    'hasUnviewed' : IDL.Bool,
  });
  const HashtagStat = IDL.Record({
    'postCount' : IDL.Nat,
    'hashtag' : IDL.Text,
  });
  const ResolveAction = IDL.Variant({
    'banUser' : IDL.Null,
    'deleteContent' : IDL.Null,
    'dismiss' : IDL.Null,
    'suspendUser' : IDL.Null,
  });
  const RespondAction = IDL.Variant({
    'accept' : IDL.Null,
    'block' : IDL.Null,
    'decline' : IDL.Null,
  });
  const SearchResults = IDL.Record({
    'users' : IDL.Vec(UserProfile),
    'posts' : IDL.Vec(PostView),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'banUser' : IDL.Func([UserId], [IDL.Bool], []),
    'blockUser' : IDL.Func([UserId], [], []),
    'cancelFriendRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createOfficialPost' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
        [],
      ),
    'createPoll' : IDL.Func(
        [PostId, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, Visibility, IDL.Vec(UserId), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
        [],
      ),
    'createStory' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [StoryView], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'editComment' : IDL.Func([CommentId, IDL.Text], [], []),
    'editPost' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
    'followUser' : IDL.Func([UserId], [IDL.Bool], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllUsers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getComments' : IDL.Func([PostId], [IDL.Vec(CommentView)], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getFriendRequestStatus' : IDL.Func([UserId], [IDL.Text], ['query']),
    'getHashtagPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'getLikes' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
    'getMessageReactions' : IDL.Func(
        [MessageId],
        [IDL.Vec(MessageReactionView)],
        ['query'],
      ),
    'getMessages' : IDL.Func([UserId], [IDL.Vec(MessageView)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyReaction' : IDL.Func([PostId], [IDL.Opt(ReactionType)], []),
    'getMyStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], []),
    'getOfficialPage' : IDL.Func([], [UserProfile], ['query']),
    'getOfficialPagePosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(FriendRequestView)],
        ['query'],
      ),
    'getPollResults' : IDL.Func([IDL.Nat], [PollResults], ['query']),
    'getPostStats' : IDL.Func([PostId], [PostStats], ['query']),
    'getReactions' : IDL.Func(
        [PostId],
        [IDL.Vec(IDL.Tuple(ReactionType, IDL.Nat))],
        ['query'],
      ),
    'getReports' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ReportView)],
        ['query'],
      ),
    'getSavedPosts' : IDL.Func([], [IDL.Vec(PostView)], []),
    'getSentRequests' : IDL.Func([], [IDL.Vec(FriendRequestView)], ['query']),
    'getShares' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getStoriesFeed' : IDL.Func([], [IDL.Vec(StoryFeed)], ['query']),
    'getStoryViewers' : IDL.Func([IDL.Nat], [IDL.Vec(UserProfile)], ['query']),
    'getTrendingHashtags' : IDL.Func([], [IDL.Vec(HashtagStat)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], []),
    'getUserPosts' : IDL.Func([UserId], [IDL.Vec(PostView)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'grantVerification' : IDL.Func([UserId], [IDL.Bool], []),
    'hasLiked' : IDL.Func([PostId], [IDL.Bool], []),
    'isBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isVerified' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'markMessageRead' : IDL.Func([MessageId], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'pinPost' : IDL.Func([PostId], [IDL.Bool], []),
    'reactToMessage' : IDL.Func([MessageId, ReactionType], [IDL.Bool], []),
    'reactToPost' : IDL.Func([PostId, ReactionType], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'removeMessageReaction' : IDL.Func([MessageId], [IDL.Bool], []),
    'removeReaction' : IDL.Func([PostId], [], []),
    'replyToComment' : IDL.Func([CommentId, IDL.Text], [CommentId], []),
    'reportPost' : IDL.Func([PostId, IDL.Text], [], []),
    'reportUser' : IDL.Func([UserId, IDL.Text], [], []),
    'resolveReport' : IDL.Func([IDL.Nat, ResolveAction], [IDL.Bool], []),
    'respondFriendRequest' : IDL.Func([IDL.Nat, RespondAction], [IDL.Bool], []),
    'revokeVerification' : IDL.Func([UserId], [IDL.Bool], []),
    'savePost' : IDL.Func([PostId], [], []),
    'searchContent' : IDL.Func([IDL.Text], [SearchResults], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'sendMessage' : IDL.Func([UserId, IDL.Vec(IDL.Nat8)], [MessageId], []),
    'sharePost' : IDL.Func([PostId], [], []),
    'suspendUser' : IDL.Func([UserId, IDL.Nat], [IDL.Bool], []),
    'unblockUser' : IDL.Func([UserId], [], []),
    'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'unpinPost' : IDL.Func([], [IDL.Bool], []),
    'unsavePost' : IDL.Func([PostId], [], []),
    'unsharePost' : IDL.Func([PostId], [], []),
    'updateAbout' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateCoverPhoto' : IDL.Func([IDL.Text], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, Visibility],
        [IDL.Bool],
        [],
      ),
    'updateProfilePhoto' : IDL.Func([IDL.Text], [], []),
    'viewStory' : IDL.Func([IDL.Nat], [], []),
    'votePoll' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };