/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'pendingReports' : bigint,
  'totalMessages' : bigint,
  'verifiedUsers' : bigint,
  'totalUsers' : bigint,
  'totalPosts' : bigint,
  'totalStories' : bigint,
}
export type CommentId = bigint;
export interface CommentView {
  'id' : CommentId,
  'content' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'updatedAt' : Timestamp,
  'replyCount' : bigint,
  'parentId' : [] | [CommentId],
  'postId' : PostId,
}
export type ConversationId = string;
export interface ConversationSummary {
  'lastMessageAt' : Timestamp,
  'otherUsername' : string,
  'lastMessagePreview' : string,
  'otherUserId' : UserId,
  'conversationId' : ConversationId,
}
export type CreateGroupResult = { 'ok' : GroupView } |
  { 'err' : string };
export type FriendRequestId = bigint;
export interface FriendRequestView {
  'id' : FriendRequestId,
  'to' : UserProfile,
  'status' : string,
  'from' : UserProfile,
  'createdAt' : Timestamp,
}
export type GroupId = bigint;
export type GroupPostId = bigint;
export interface GroupPostView {
  'id' : GroupPostId,
  'authorVerified' : boolean,
  'content' : string,
  'authorProfilePhoto' : [] | [string],
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'updatedAt' : Timestamp,
  'imageUrl' : [] | [string],
  'groupId' : GroupId,
  'commentsCount' : bigint,
  'likesCount' : bigint,
}
export interface GroupView {
  'id' : GroupId,
  'coverImageUrl' : [] | [string],
  'coverImageData' : [] | [string],
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'memberCount' : bigint,
  'isMember' : boolean,
  'description' : string,
  'isPrivate' : boolean,
  'hasCoverImage' : boolean,
  'ownerUsername' : string,
}
export interface HashtagStat { 'postCount' : bigint, 'hashtag' : string }
export type JoinLeaveGroupResult = { 'ok' : boolean } |
  { 'err' : string };
export type LoginWithPasswordResult = {
    'ok' : { 'userId' : UserId, 'profile' : UserProfile }
  } |
  { 'err' : string };
export type MessageId = bigint;
export interface MessageReactionView {
  'reactor' : UserProfile,
  'reaction' : string,
}
export interface MessageView {
  'id' : MessageId,
  'encryptedContent' : Uint8Array,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'conversationId' : ConversationId,
  'senderId' : UserId,
  'readAt' : [] | [Timestamp],
}
export type NotificationId = bigint;
export type NotificationType = { 'verified' : {} } |
  { 'like' : { 'postId' : PostId } } |
  { 'newUserRegistration' : { 'fromUsername' : string } } |
  { 'share' : { 'postId' : PostId } } |
  { 'comment' : { 'commentId' : CommentId, 'postId' : PostId } } |
  { 'mention' : { 'postId' : PostId } } |
  { 'friendRequest' : { 'requestId' : bigint } } |
  { 'reaction' : { 'reaction' : ReactionType, 'postId' : PostId } } |
  { 'follow' : {} };
export interface NotificationView {
  'id' : NotificationId,
  'actorName' : string,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'actorId' : UserId,
}
export type PageId = bigint;
export interface PageView {
  'id' : PageId,
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isVerified' : boolean,
  'isFollowing' : boolean,
  'category' : string,
  'followerCount' : bigint,
  'profilePhotoUrl' : [] | [string],
  'coverPhotoUrl' : [] | [string],
}
export interface PollOptionResult {
  'id' : bigint,
  'votes' : bigint,
  'text' : string,
  'percent' : number,
}
export interface PollResults {
  'totalVotes' : bigint,
  'myVote' : [] | [bigint],
  'options' : Array<PollOptionResult>,
}
export type PostId = bigint;
export interface PostStats {
  'shares' : bigint,
  'likes' : bigint,
  'comments' : bigint,
}
export interface PostView {
  'id' : PostId,
  'authorVerified' : boolean,
  'content' : string,
  'authorProfilePhoto' : [] | [string],
  'originalPostId' : [] | [PostId],
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'isRepost' : boolean,
  'updatedAt' : Timestamp,
  'imageUrl' : [] | [string],
  'visibility' : Visibility,
  'isPinned' : boolean,
}
export type ReactionType = { 'sad' : null } |
  { 'wow' : null } |
  { 'angry' : null } |
  { 'haha' : null } |
  { 'like' : null } |
  { 'love' : null };
export interface ReportView {
  'id' : bigint,
  'status' : string,
  'reportedPost' : [] | [PostView],
  'reportedUser' : [] | [UserProfile],
  'createdAt' : Timestamp,
  'reporter' : UserProfile,
  'reason' : string,
}
export type ResolveAction = { 'banUser' : null } |
  { 'deleteContent' : null } |
  { 'dismiss' : null } |
  { 'suspendUser' : null };
export type RespondAction = { 'accept' : null } |
  { 'block' : null } |
  { 'decline' : null };
export interface SearchResults {
  'users' : Array<UserProfile>,
  'posts' : Array<PostView>,
}
export interface StoryFeed {
  'stories' : Array<StoryView>,
  'author' : UserProfile,
  'hasUnviewed' : boolean,
}
export type StoryId = bigint;
export interface StoryView {
  'id' : StoryId,
  'expiresAt' : Timestamp,
  'viewedByMe' : boolean,
  'createdAt' : Timestamp,
  'author' : UserProfile,
  'imageUrl' : string,
  'textOverlay' : [] | [string],
  'viewCount' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'postCount' : bigint,
  'username' : string,
  'aboutWebsite' : [] | [string],
  'birthdate' : [] | [string],
  'isOfficialPage' : boolean,
  'isVerified' : boolean,
  'aboutBio' : [] | [string],
  'aboutWork' : [] | [string],
  'aboutLocation' : [] | [string],
  'followerCount' : bigint,
  'followingCount' : bigint,
  'profilePhotoUrl' : [] | [string],
  'visibility' : Visibility,
  'coverPhotoUrl' : [] | [string],
  'aboutEducation' : [] | [string],
}
export type Visibility = { 'everyone' : null } |
  { 'followersOnly' : null } |
  { 'friendsOnly' : null } |
  { 'customList' : null };
export interface _SERVICE {
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'banUser' : ActorMethod<[UserId], boolean>,
  'blockUser' : ActorMethod<[UserId], undefined>,
  'cancelFriendRequest' : ActorMethod<[bigint], boolean>,
  'createGroup' : ActorMethod<
    [string, string, boolean, [] | [string]],
    CreateGroupResult
  >,
  'createGroupPost' : ActorMethod<
    [GroupId, string, [] | [string]],
    { 'ok' : GroupPostId } |
      { 'err' : string }
  >,
  'createOfficialPost' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : PostId } |
      { 'err' : string }
  >,
  'createPage' : ActorMethod<
    [string, string, string],
    { 'ok' : PageView } |
      { 'err' : string }
  >,
  'createPagePost' : ActorMethod<
    [PageId, string],
    { 'ok' : PostView } |
      { 'err' : string }
  >,
  'createPoll' : ActorMethod<[PostId, string, Array<string>], bigint>,
  'createPost' : ActorMethod<
    [string, Visibility, Array<UserId>, [] | [string]],
    { 'ok' : PostId } |
      { 'err' : string }
  >,
  'createStory' : ActorMethod<[string, [] | [string]], StoryView>,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deleteGroup' : ActorMethod<[GroupId], boolean>,
  'deleteGroupPost' : ActorMethod<
    [GroupId, GroupPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deletePost' : ActorMethod<[PostId], boolean>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[UserId], boolean>,
  'editComment' : ActorMethod<[CommentId, string], undefined>,
  'editGroupPost' : ActorMethod<
    [GroupId, GroupPostId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'editPost' : ActorMethod<[PostId, string], boolean>,
  'editPostWithImage' : ActorMethod<[PostId, string, [] | [string]], boolean>,
  'ensureOwnerAccount' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'followPage' : ActorMethod<[PageId], { 'ok' : null } | { 'err' : string }>,
  'followUser' : ActorMethod<[UserId], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllUsers' : ActorMethod<[bigint, bigint], Array<UserProfile>>,
  'getComments' : ActorMethod<[PostId], Array<CommentView>>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getFeed' : ActorMethod<[], Array<PostView>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserProfile>>,
  'getFriendRequestStatus' : ActorMethod<[UserId], string>,
  'getGroup' : ActorMethod<[GroupId], [] | [GroupView]>,
  'getGroupPosts' : ActorMethod<[GroupId], Array<GroupPostView>>,
  'getGroups' : ActorMethod<[], Array<GroupView>>,
  'getGroupsPaginated' : ActorMethod<[bigint, bigint], Array<GroupView>>,
  'getHashtagPosts' : ActorMethod<[string], Array<PostView>>,
  'getLikes' : ActorMethod<[PostId], Array<UserId>>,
  'getMessageReactions' : ActorMethod<[MessageId], Array<MessageReactionView>>,
  'getMessages' : ActorMethod<[UserId], Array<MessageView>>,
  'getMyEmail' : ActorMethod<[], [] | [string]>,
  'getMyGroups' : ActorMethod<[], Array<GroupView>>,
  'getMyPages' : ActorMethod<[], Array<PageView>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyReaction' : ActorMethod<[PostId], [] | [ReactionType]>,
  'getMyStories' : ActorMethod<[], Array<StoryView>>,
  'getNotifications' : ActorMethod<[], Array<NotificationView>>,
  'getOfficialPage' : ActorMethod<[], UserProfile>,
  'getOfficialPageLink' : ActorMethod<[], string>,
  'getOfficialPagePosts' : ActorMethod<[bigint, bigint], Array<PostView>>,
  'getPage' : ActorMethod<[PageId], [] | [PageView]>,
  'getPagePosts' : ActorMethod<[PageId], Array<PostView>>,
  'getPendingRequests' : ActorMethod<[], Array<FriendRequestView>>,
  'getPollResults' : ActorMethod<[bigint], PollResults>,
  'getPostStats' : ActorMethod<[PostId], PostStats>,
  'getProfileLink' : ActorMethod<[UserId], string>,
  'getReactions' : ActorMethod<[PostId], Array<[ReactionType, bigint]>>,
  'getReports' : ActorMethod<[bigint, bigint], Array<ReportView>>,
  'getSavedPosts' : ActorMethod<[], Array<PostView>>,
  'getSentRequests' : ActorMethod<[], Array<FriendRequestView>>,
  'getShares' : ActorMethod<[PostId], bigint>,
  'getStoriesFeed' : ActorMethod<[], Array<StoryFeed>>,
  'getStoryViewers' : ActorMethod<[bigint], Array<UserProfile>>,
  'getTrendingHashtags' : ActorMethod<[], Array<HashtagStat>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserPosts' : ActorMethod<[UserId], Array<PostView>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'grantVerification' : ActorMethod<[UserId], boolean>,
  'hasLiked' : ActorMethod<[PostId], boolean>,
  'inviteMember' : ActorMethod<[GroupId, string], JoinLeaveGroupResult>,
  'isBlocked' : ActorMethod<[UserId], boolean>,
  'isFollowing' : ActorMethod<[UserId], boolean>,
  'isVerified' : ActorMethod<[UserId], boolean>,
  'joinGroup' : ActorMethod<[GroupId], JoinLeaveGroupResult>,
  'leaveGroup' : ActorMethod<[GroupId], JoinLeaveGroupResult>,
  'likeGroupPost' : ActorMethod<
    [GroupId, GroupPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'likePost' : ActorMethod<[PostId], undefined>,
  'loginWithPassword' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'loginWithPasswordOnly' : ActorMethod<
    [string, string],
    LoginWithPasswordResult
  >,
  'markMessageRead' : ActorMethod<[MessageId], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'ownerAccountExists' : ActorMethod<[], boolean>,
  'pinPost' : ActorMethod<[PostId], boolean>,
  'ping' : ActorMethod<[], boolean>,
  'reactToMessage' : ActorMethod<[MessageId, ReactionType], boolean>,
  'reactToPost' : ActorMethod<[PostId, ReactionType], undefined>,
  'register' : ActorMethod<[string, string], boolean>,
  'registerWithPassword' : ActorMethod<
    [string, string, string, [] | [string]],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'removeMessageReaction' : ActorMethod<[MessageId], boolean>,
  'removeReaction' : ActorMethod<[PostId], undefined>,
  'replyToComment' : ActorMethod<[CommentId, string], CommentId>,
  'reportPost' : ActorMethod<[PostId, string], undefined>,
  'reportUser' : ActorMethod<[UserId, string], undefined>,
  'resolveReport' : ActorMethod<[bigint, ResolveAction], boolean>,
  'respondFriendRequest' : ActorMethod<[bigint, RespondAction], boolean>,
  'revokeVerification' : ActorMethod<[UserId], boolean>,
  'savePost' : ActorMethod<[PostId], undefined>,
  'searchContent' : ActorMethod<[string], SearchResults>,
  'searchPages' : ActorMethod<[string], Array<PageView>>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendFriendRequest' : ActorMethod<[UserId], boolean>,
  'sendMessage' : ActorMethod<[UserId, Uint8Array], MessageId>,
  'setMyPassword' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'sharePost' : ActorMethod<[PostId], undefined>,
  'sharePostToFeed' : ActorMethod<
    [PostId, string],
    { 'ok' : PostView } |
      { 'err' : string }
  >,
  'suspendUser' : ActorMethod<[UserId, bigint], boolean>,
  'unblockUser' : ActorMethod<[UserId], undefined>,
  'unfollowPage' : ActorMethod<[PageId], { 'ok' : null } | { 'err' : string }>,
  'unfollowUser' : ActorMethod<[UserId], boolean>,
  'unlikeGroupPost' : ActorMethod<
    [GroupId, GroupPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'unpinPost' : ActorMethod<[], boolean>,
  'unsavePost' : ActorMethod<[PostId], undefined>,
  'unsharePost' : ActorMethod<[PostId], undefined>,
  'updateAbout' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string], [] | [string]],
    boolean
  >,
  'updateCoverPhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateEmail' : ActorMethod<[string], boolean>,
  'updateGroupCoverImage' : ActorMethod<
    [GroupId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOfficialPageCoverPhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOfficialPageProfilePhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePage' : ActorMethod<
    [PageId, string, string],
    { 'ok' : PageView } |
      { 'err' : string }
  >,
  'updatePageCoverPhoto' : ActorMethod<
    [PageId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePageProfilePhoto' : ActorMethod<
    [PageId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<[string, string, Visibility], boolean>,
  'updateProfilePhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifySession' : ActorMethod<[UserId], [] | [UserProfile]>,
  'viewStory' : ActorMethod<[bigint], undefined>,
  'votePoll' : ActorMethod<[bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];